# Generated by Django 5.2.8 on 2025-11-17 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=13, verbose_name='電話番号')),
                ('birthdate', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('female', '女性'), ('male', '男性')], max_length=10, verbose_name='性別')),
                ('card_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='診察券番号')),
                ('is_active', models.BooleanField(default=True, help_text='※Web予約システムにログインできるかを指定します。\n※退会の場合は選択を解除します。', verbose_name='予約システムのログイン権限')),
                ('is_staff', models.BooleanField(default=False, help_text='※この管理画面にログインできるかを指定します。', verbose_name='管理画面のアクセス権限')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '01. 登録ユーザー',
                'verbose_name_plural': '01. 登録ユーザー',
            },
        ),
    ]
