# Generated by Django 5.2.8 on 2025-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '登録ユーザー', 'verbose_name_plural': '登録ユーザー'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='※ネット予約にログインできるかを指定します。<br>※退会の場合はチェックを解除します。', verbose_name='ログイン権限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='※この管理画面にログインできるかを指定します。<br>※ログイン権限にもチェックを入れることが必須です。', verbose_name='管理画面のアクセス権限'),
        ),
    ]
