# Generated by Django 5.2.8 on 2025-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_name_customuser_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='family_name',
            field=models.CharField(max_length=100, verbose_name='お名前 （姓）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='お名前 （名）'),
        ),
    ]
