# Generated by Django 5.2.8 on 2025-11-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewYearClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '年末年始休診',
                'verbose_name_plural': '年末年始休診',
            },
        ),
        migrations.CreateModel(
            name='RegularClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', '月曜日'), ('tuesday', '火曜日'), ('wednesday', '水曜日'), ('thursday', '木曜日'), ('friday', '金曜日'), ('saturday', '土曜日'), ('sunday', '日曜日'), ('holiday', '祝日')], max_length=10, verbose_name='休診の曜日')),
                ('closed_hours', models.CharField(choices=[('morning', '午前休診'), ('afternoon', '午後休診'), ('all_day', '終日休診')], default='both', max_length=10, verbose_name='休診の時間帯')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '休診日',
                'verbose_name_plural': '休診日',
            },
        ),
        migrations.CreateModel(
            name='SummerClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '夏季休診',
                'verbose_name_plural': '夏季休診',
            },
        ),
        migrations.CreateModel(
            name='TempClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='臨時休診日')),
                ('closed_hours', models.CharField(choices=[('morning', '午前休診'), ('afternoon', '午後休診'), ('all_day', '終日休診')], default='both', max_length=10, verbose_name='休診時間帯')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '臨時休診日',
                'verbose_name_plural': '臨時休診日',
            },
        ),
    ]
