# Generated by Django 5.2.8 on 2025-11-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclosing',
            name='closed_hours',
            field=models.CharField(choices=[('morning', '午前休診'), ('afternoon', '午後休診'), ('all_day', '終日休診')], default='all_day', max_length=10, verbose_name='休診の時間帯'),
        ),
        migrations.AlterField(
            model_name='regularclosing',
            name='weekday',
            field=models.CharField(choices=[('monday', '月曜日'), ('tuesday', '火曜日'), ('wednesday', '水曜日'), ('thursday', '木曜日'), ('friday', '金曜日'), ('saturday', '土曜日'), ('sunday', '日曜日'), ('holiday', '祝日')], max_length=10, unique=True, verbose_name='休診の曜日'),
        ),
        migrations.AlterField(
            model_name='tempclosing',
            name='closed_hours',
            field=models.CharField(choices=[('morning', '午前休診'), ('afternoon', '午後休診'), ('all_day', '終日休診')], default='all_day', max_length=10, verbose_name='休診時間帯'),
        ),
        migrations.AlterField(
            model_name='tempclosing',
            name='date',
            field=models.DateField(unique=True, verbose_name='臨時休診日'),
        ),
    ]
