# Generated by Django 5.2.8 on 2025-11-29 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_regularclosing_closed_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(choices=[('first', '初診'), ('return', '再診')], max_length=100, verbose_name='初診 または 再診')),
                ('datetime', models.DateTimeField(verbose_name='来院日時')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='お名前 （姓）')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='お名前 （名）')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='電話番号')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('female', '女性'), ('male', '男性')], max_length=10, null=True, verbose_name='性別')),
                ('card_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='診察券番号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='受付日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '診察予約',
                'verbose_name_plural': '診察予約',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.JSONField(default=list, verbose_name='本日はどうなさいましたか？')),
                ('symptom_other', models.CharField(blank=True, null=True, verbose_name='本日はどうなさいましたか？（その他）')),
                ('symptom_start', models.DateField(verbose_name='症状はいつ頃からありますか？')),
                ('medical_history', models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='過去に大きな病気で治療や手術を受けられたことはありますか？')),
                ('has_medical_history', models.CharField(blank=True, null=True, verbose_name='過去に大きな病気で治療や手術を受けられたことはありますか？（ある）')),
                ('under_treatment', models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='現在、治療中の病気はありますか？')),
                ('has_under_treatment', models.CharField(blank=True, null=True, verbose_name='現在、治療中の病気はありますか？（ある）')),
                ('current_medication', models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='現在、飲んでいるお薬はありますか？')),
                ('has_current_medication', models.CharField(blank=True, null=True, verbose_name='現在、飲んでいるお薬はありますか？（ある）')),
                ('smoking', models.CharField(choices=[('no-smoking', '吸わない'), ('smoking', '吸う'), ('quit-smoking', '禁煙した')], max_length=100, verbose_name='煙草')),
                ('has_smoking_per_day', models.CharField(blank=True, choices=[('', '---'), ('1', '1本'), ('2', '2本'), ('3', '3本'), ('4', '4本'), ('5', '5本'), ('6', '6本'), ('7', '7本'), ('8', '8本'), ('9', '9本'), ('10', '10本'), ('11', '11本'), ('12', '12本'), ('13', '13本'), ('14', '14本'), ('15', '15本'), ('16', '16本'), ('17', '17本'), ('18', '18本'), ('19', '19本'), ('20_over', '20本以上')], max_length=100, null=True, verbose_name='1日の喫煙本数')),
                ('has_smoking_years', models.CharField(blank=True, choices=[('', '---'), ('1_under', '1年未満'), ('2', '2年間'), ('3', '3年間'), ('4', '4年間'), ('5', '5年間'), ('6', '6年間'), ('7', '7年間'), ('8', '8年間'), ('9', '9年間'), ('10', '10年間'), ('11', '11年間'), ('12', '12年間'), ('13', '13年間'), ('14', '14年間'), ('15', '15年間'), ('16', '16年間'), ('17', '17年間'), ('18', '18年間'), ('19', '19年間'), ('20_over', '20年以上')], max_length=100, null=True, verbose_name='喫煙の期間')),
                ('has_quit_smoking_years', models.CharField(blank=True, choices=[('', '---'), ('1', '1年'), ('2', '2年'), ('3', '3年'), ('4', '4年'), ('5', '5年'), ('6', '6年'), ('7', '7年'), ('8', '8年'), ('9', '9年'), ('10', '10年'), ('11', '11年'), ('12', '12年'), ('13', '13年'), ('14', '14年'), ('15', '15年'), ('16', '16年'), ('17', '17年'), ('18', '18年'), ('19', '19年'), ('20_over', '20年以上')], max_length=100, null=True, verbose_name='禁煙の期間')),
                ('has_until_smoking_years', models.CharField(blank=True, choices=[('', '---'), ('1_under', '1年未満'), ('2', '2年間'), ('3', '3年間'), ('4', '4年間'), ('5', '5年間'), ('6', '6年間'), ('7', '7年間'), ('8', '8年間'), ('9', '9年間'), ('10', '10年間'), ('11', '11年間'), ('12', '12年間'), ('13', '13年間'), ('14', '14年間'), ('15', '15年間'), ('16', '16年間'), ('17', '17年間'), ('18', '18年間'), ('19', '19年間'), ('20_over', '20年以上')], max_length=100, null=True, verbose_name='禁煙するまでの喫煙期間')),
                ('alcohol', models.CharField(choices=[('no', '飲まない'), ('yes', '飲む')], max_length=100, verbose_name='飲酒')),
                ('alcohol_per_week', models.CharField(blank=True, choices=[('', '---'), ('1', '1日'), ('2', '2日'), ('3', '3日'), ('4', '4日'), ('5', '5日'), ('6', '6日'), ('7', '7日')], max_length=100, null=True, verbose_name='1週間の飲酒の頻度')),
                ('alcohol_type', models.CharField(blank=True, null=True, verbose_name='飲酒の種類')),
                ('alcohol_amount', models.CharField(blank=True, null=True, verbose_name='飲酒の量')),
                ('allergy', models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='お薬・食べ物のアレルギーはありますか？')),
                ('has_allergy', models.CharField(blank=True, null=True, verbose_name='お薬・食べ物のアレルギーはありますか？（ある）')),
                ('pregnancy', models.CharField(choices=[('no', 'いいえ'), ('now', '妊娠中'), ('possible', '妊娠の可能性'), ('breastfeeding', '授乳中')], max_length=100, verbose_name='現在、妊娠中あるいは妊娠の可能性、または授乳中ですか？')),
                ('especially', models.TextField(blank=True, null=True, verbose_name='特に調べてほしいこと、検査、治療がありましたらご記入ください')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='受付日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
            ],
            options={
                'verbose_name': '問診票',
                'verbose_name_plural': '問診票',
            },
        ),
    ]
