# Generated by Django 5.2.8 on 2025-11-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_questionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='appointment_dt',
        ),
    ]
