# Generated by Django 5.2.8 on 2025-11-29 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_datetime_appointment_appointment_dt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='allergy',
            field=models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='ある / ない'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.appointment', verbose_name='予約情報'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='current_medication',
            field=models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='飲んでいるお薬'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='especially',
            field=models.TextField(blank=True, null=True, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='has_allergy',
            field=models.CharField(blank=True, null=True, verbose_name='お薬・食べ物のアレルギー'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='has_current_medication',
            field=models.CharField(blank=True, null=True, verbose_name='飲んでいるお薬'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='has_medical_history',
            field=models.CharField(blank=True, null=True, verbose_name='過去の治療や手術'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='has_under_treatment',
            field=models.CharField(blank=True, null=True, verbose_name='ある / ない'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='medical_history',
            field=models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='ある / ない'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='pregnancy',
            field=models.CharField(choices=[('no', 'いいえ'), ('now', '妊娠中'), ('possible', '妊娠の可能性'), ('breastfeeding', '授乳中')], max_length=100, verbose_name='妊娠について'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='symptom',
            field=models.JSONField(default=list, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='symptom_other',
            field=models.CharField(blank=True, null=True, verbose_name='その他の症状'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='symptom_start',
            field=models.DateField(verbose_name='はじまりの時期'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='under_treatment',
            field=models.CharField(choices=[('no', 'ない'), ('yes', 'ある')], max_length=100, verbose_name='ある / ない'),
        ),
    ]
