"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app.apps.AppConfig",
    "django.contrib.humanize",
    "rangefilter",
    "django.contrib.sites",
    "app.accounts.apps.AccountsConfig",
    "allauth",
    "allauth.account",
    "widget_tweaks",
    "django_recaptcha",
    "django.contrib.sitemaps",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "admin", "templates"),
        ],
        "OPTIONS": {
            "context_processors": [
                "app.context_processors.settings_context",  # 追加
            ],
        },
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "app.accounts.validators.CustomPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 数字のカンマ区切り
NUMBER_GROUPING = 3

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# ユーザーモデルにusernameフィールドは無いことを明示
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# ユーザー認証にメールアドレスを使用
ACCOUNT_LOGIN_METHODS = {"email"}

# 利用登録の必須項目
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]

# メールアドレスの確認は送信するけど確認は任意（ログインはis_activeで制御）
ACCOUNT_EMAIL_VERIFICATION = "optional"

# ログイン回数制限（10分間に5回まで）
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/10m",
}

# カスタムユーザーを認証に指定
AUTH_USER_MODEL = "accounts.CustomUser"

# 登録済みメールアドレスのエラーを表示
ACCOUNT_PREVENT_ENUMERATION = False

# ログインページ
LOGIN_URL = "/"

# ログイン後のリダイレクトページ
LOGIN_REDIRECT_URL = "/mypage/"

# ログアウト後のリダイレクトページ
ACCOUNT_LOGOUT_REDIRECT_URL = "/logout/"

# パスワードリセットメールのトークン有効期限
PASSWORD_RESET_TIMEOUT = 3600 * 24

# マッピングを定義
GENDER_CHOICES = (
    ("female", "女性"),
    ("male", "男性"),
)
VISIT_CHOICES = (
    ("first", "初診"),
    ("return", "再診"),
)
SYMTOM_CHOICES = (
    ("fever", "熱"),
    ("sore_throat", "喉の痛み"),
    ("headache", "頭痛"),
    ("runny_nose_congestion", "鼻水・鼻づまり"),
    ("cough_phlegm", "咳・たん"),
    ("nausea", "吐き気"),
    ("diarrhea", "下痢"),
    ("abdominal_pain", "腹痛"),
    ("stomach_pain", "胃痛"),
    ("heartburn", "胸やけ"),
    ("palpitations_dyspnea", "動悸・息切れ"),
    ("swelling", "むくみ"),
    ("dizziness", "めまい"),
    ("other", "その他"),
)
YES_OR_NO_CHOICES = (
    ("no", "ない"),
    ("yes", "ある"),
)
SMOKING_CHOICES = (
    ("no-smoking", "吸わない"),
    ("smoking", "吸う"),
    ("quit-smoking", "禁煙した"),
)
SMOKING_PER_DAY_CHOICES = (
    [("", "---")] + [(str(i), f"{i}本") for i in range(1, 20)] + [("20_over", "20本以上")]
)
YEARS_CHOICES = (
    [("", "---"), ("1_under", "1年未満")] + [(str(i), f"{i}年間") for i in range(2, 20)] + [("20_over", "20年以上")]
)
QUIT_SMOKING_YEARS_CHOICES = (
    [("", "---")] + [(str(i), f"{i}年") for i in range(1, 20)] + [("20_over", "20年以上")]
)
ALCOHOL_CHOICES = (
    ("no", "飲まない"),
    ("yes", "飲む"),
)
ALCOHOL_PER_WEEK_CHOICES = [("", "---")] + [(str(i), f"{i}日") for i in range(1, 8)]
PREGNANCY_CHOICES = (
    ("no", "いいえ"),
    ("now", "妊娠中"),
    ("possible", "妊娠の可能性"),
    ("breastfeeding", "授乳中"),
)
CLOSED_WEEKDAY_CHOICES = (
    ("monday", "月曜日"),
    ("tuesday", "火曜日"),
    ("wednesday", "水曜日"),
    ("thursday", "木曜日"),
    ("friday", "金曜日"),
    ("saturday", "土曜日"),
    ("sunday", "日曜日"),
    ("holiday", "祝日"),
)
CLOSED_TIME_CHOICES = (
    ("morning", "午前休診"),
    ("afternoon", "午後休診"),
    ("all_day", "終日休診"),
)

# 診察時間帯を定義
TIME_LIST = ["09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"]

# 曜日を日本語の略称で定義
WEEKDAYS = ["月", "火", "水", "木", "金", "土", "日"]

# 各曜日とモデルの曜日フィールドのマッピング
MODEL_WEEKDAY_MAP = {
    0: "monday",
    1: "tuesday",
    2: "wednesday",
    3: "thursday",
    4: "friday",
    5: "saturday",
    6: "sunday",
}

# セッションの有効期限
SESSION_AGE_TIME = 60

try:
    from .local_settings import *
except ImportError:
    pass

if DEBUG:
    ALLOWED_HOSTS = ["*"]
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
    # メール送信
    # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

    # ログ
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        # ログ出力フォーマットの設定
        "formatters": {
            "develop": {"format": "[%(asctime)s] %(message)s"},
        },
        # ハンドラの設定
        "handlers": {
            # コンソールは常にDEBUGまで出す（本番・開発共通）
            "console": {
                "class": "logging.StreamHandler",
                "stream": "ext://sys.stdout",
                "level": "DEBUG",
                "formatter": "develop",
            },
        },
        # ルートロガーはDEBUG（各ハンドラで振り分け）
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        # ロガーの設定
        "loggers": {
            "django": {"level": "INFO", "propagate": True},
            "django.server": {"handlers": ["console"], "level": "INFO", "propagate": False},
        },
    }

else:
    import environ

    env = environ.Env()
    env.read_env(os.path.join(BASE_DIR, ".env"))

    SECRET_KEY = env("SECRET_KEY")
    BASE_URL = env("BASE_URL")
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
    STATIC_ROOT = env("STATIC_ROOT")

    DATABASES = {
        "default": env.db(),
    }

    # メール送信
    SITE_NAME = env("SITE_NAME")
    EMAIL_HOST = env("EMAIL_HOST")
    EMAIL_PORT = env("EMAIL_PORT")
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = env("EMAIL_USE_TLS")
    FROM_EMAIL = SITE_NAME + "<" + EMAIL_HOST_USER + ">"
    TO_EMAIL = env("TO_EMAIL")

    # reCAPTCHA
    RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
    RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")

    # ログ
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        # ログ出力フォーマットの設定
        "formatters": {
            "production": {"format": "%(asctime)s [%(levelname)s] %(pathname)s:%(lineno)d %(message)s"},
        },
        # ハンドラの設定
        "handlers": {
            # コンソールは常にDEBUGまで出す（本番・開発共通）
            "console": {
                "class": "logging.StreamHandler",
                "stream": "ext://sys.stdout",
                "level": "DEBUG",
                "formatter": "production",
            },
            # ファイルはINFO以上だけ残す
            "file": {
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": BASE_DIR / "logging" / "app.log",
                "when": "midnight",  # 毎日0時で切り替え
                "backupCount": 14,  # 14日分だけ保持
                "level": "INFO",
                "formatter": "production",
                "encoding": "utf-8",
            },
        },
        # ルートロガーはDEBUG（各ハンドラで振り分け）
        "root": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
        },
        # ロガーの設定
        "loggers": {
            "django": {"level": "INFO", "propagate": True},
            "django.server": {"handlers": ["console"], "level": "INFO", "propagate": False},
        },
    }
