"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app.apps.AppConfig",
    "django.contrib.humanize",
    "rangefilter",
    "django.contrib.sites",
    "app.accounts.apps.AccountsConfig",
    "allauth",
    "allauth.account",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "admin", "templates"),
        ],
        "OPTIONS": {
            "context_processors": [
                "app.context_processors.settings_context",  # 追加
            ],
        },
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "app.accounts.validators.CustomPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 数字のカンマ区切り
NUMBER_GROUPING = 3

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# ユーザーモデルにusernameフィールドは無いことを明示
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  

# ユーザー認証にメールアドレスを使用
ACCOUNT_LOGIN_METHODS = {"email"}

# 利用登録の必須項目
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]

# メールアドレスの確認は送信するけど確認は任意（ログインはis_activeで制御）
ACCOUNT_EMAIL_VERIFICATION = "optional"

# ログイン回数制限（10分間に5回まで）
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/10m",
}

# カスタムユーザーを認証に指定
AUTH_USER_MODEL = "accounts.CustomUser"

# 登録済みメールアドレスのエラーを表示
ACCOUNT_PREVENT_ENUMERATION = False

# ログイン後のリダイレクトページ
LOGIN_REDIRECT_URL = "/mypage/"

# ログアウト後のリダイレクトページ
ACCOUNT_LOGOUT_REDIRECT_URL = "/logout/"

# マッピングを定義
GENDER_CHOICES = (
    ("female", "女性"),
    ("male", "男性"),
)

try:
    from .local_settings import *
except ImportError:
    pass

# 既定のメール送信アドレス
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

if DEBUG:
    ALLOWED_HOSTS = ["*"]
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
    # メール送信
    # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

    # ログ
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        # ログ出力フォーマットの設定
        "formatters": {
            "develop": {"format": "[%(asctime)s] %(message)s"},
        },
        # ハンドラの設定
        "handlers": {
            # コンソールは常にDEBUGまで出す（本番・開発共通）
            "console": {
                "class": "logging.StreamHandler",
                "stream": "ext://sys.stdout",
                "level": "DEBUG",
                "formatter": "develop",
            },
        },
        # ルートロガーはDEBUG（各ハンドラで振り分け）
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        # ロガーの設定
        "loggers": {
            "django": {"level": "INFO", "propagate": True},
            "django.server": {"handlers": ["console"], "level": "INFO", "propagate": False},
        },
    }

else:
    import environ

    env = environ.Env()
    env.read_env(os.path.join(BASE_DIR, ".env"))

    SECRET_KEY = env("SECRET_KEY")
    BASE_URL = env("BASE_URL")
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
    STATIC_ROOT = env("STATIC_ROOT")

    DATABASES = {
        "default": env.db(),
    }

    # メール送信
    SITE_NAME = env("SITE_NAME")
    EMAIL_HOST = env("EMAIL_HOST")
    EMAIL_PORT = env("EMAIL_PORT")
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = env("EMAIL_USE_TLS")
    FROM_EMAIL = SITE_NAME + "<" + EMAIL_HOST_USER + ">"
    TO_EMAIL = env("TO_EMAIL")

    # ログ
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        # ログ出力フォーマットの設定
        "formatters": {
            "production": {"format": "%(asctime)s [%(levelname)s] %(pathname)s:%(lineno)d %(message)s"},
        },
        # ハンドラの設定
        "handlers": {
            # コンソールは常にDEBUGまで出す（本番・開発共通）
            "console": {
                "class": "logging.StreamHandler",
                "stream": "ext://sys.stdout",
                "level": "DEBUG",
                "formatter": "production",
            },
            # ファイルはINFO以上だけ残す
            "file": {
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": "app.log",
                "when": "midnight",  # 毎日0時で切り替え
                "backupCount": 14,  # 14日分だけ保持
                "level": "INFO",
                "formatter": "production",
                "encoding": "utf-8",
            },
        },
        # ルートロガーはDEBUG（各ハンドラで振り分け）
        "root": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
        },
        # ロガーの設定
        "loggers": {
            "django": {"level": "INFO", "propagate": True},
            "django.server": {"handlers": ["console"], "level": "INFO", "propagate": False},
        },
    }
